"""
LEMP Stack (Linux, Nginx, MySQL, PHP)

Complete LEMP stack deployment for web applications.

Components:
- Nginx web server
- MySQL database
- PHP-FPM
- Sample PHP application

Usage:
    sudo cook plan examples/lemp-stack.py
    sudo cook apply examples/lemp-stack.py --yes

After deployment:
    curl http://localhost
"""

from cook import Package, File, Service, Exec
import os

# Configuration
DOMAIN = os.getenv("DOMAIN", "localhost")
WEB_ROOT = "/var/www/html"
MYSQL_ROOT_PASSWORD = os.getenv("MYSQL_ROOT_PASSWORD", "secure_root_password_change_me")

# Package Installation

print("Installing LEMP stack packages")

# Nginx
Package("nginx")

# MySQL
Package("mysql-server", packages=[
    "mysql-server",
    "mysql-client",
])

# PHP and common extensions
Package("php", packages=[
    "php-fpm",
    "php-mysql",
    "php-curl",
    "php-gd",
    "php-mbstring",
    "php-xml",
    "php-xmlrpc",
    "php-zip",
    "php-json",
])

# MySQL Setup

print("Configuring MySQL")

# Secure MySQL installation
Exec("mysql-secure",
     command=f"""mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{MYSQL_ROOT_PASSWORD}';" """,
     unless=f"mysqladmin -u root -p{MYSQL_ROOT_PASSWORD} ping 2>/dev/null")

# Remove anonymous users
Exec("mysql-remove-anonymous",
     command="""mysql -u root -p{} -e "DELETE FROM mysql.user WHERE User='';" """.format(MYSQL_ROOT_PASSWORD))

# Remove test database
Exec("mysql-remove-test-db",
     command="""mysql -u root -p{} -e "DROP DATABASE IF EXISTS test;" """.format(MYSQL_ROOT_PASSWORD),
     unless="! mysql -u root -p{} -e 'SHOW DATABASES' | grep -q test".format(MYSQL_ROOT_PASSWORD))

# Flush privileges
Exec("mysql-flush-privileges",
     command="""mysql -u root -p{} -e "FLUSH PRIVILEGES;" """.format(MYSQL_ROOT_PASSWORD))

# MySQL service
Service("mysql",
        running=True,
        enabled=True)

# Web Directory Setup

print("Setting up web directory")

# Create web root
File(WEB_ROOT,
     ensure="directory",
     mode=0o755,
     owner="www-data",
     group="www-data")

# Create sample PHP application
php_app = File(
    f"{WEB_ROOT}/index.php",
    content="""<?php
/**
 * Sample LEMP Stack Application
 * Generated by Cook
 */

// PHP info
$php_version = phpversion();
$mysql_available = extension_loaded('mysqli') ? 'Yes' : 'No';

// Server info
$server_software = $_SERVER['SERVER_SOFTWARE'] ?? 'Unknown';
$document_root = $_SERVER['DOCUMENT_ROOT'] ?? 'Unknown';

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LEMP Stack - Cook</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background: #f5f5f5;
        }
        .container {
            background: white;
            border-radius: 8px;
            padding: 30px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        h1 { color: #333; border-bottom: 3px solid #4CAF50; padding-bottom: 10px; }
        .info-grid {
            display: grid;
            grid-template-columns: 200px 1fr;
            gap: 15px;
            margin: 20px 0;
        }
        .label { font-weight: bold; color: #666; }
        .value { color: #333; }
        .success { color: #4CAF50; }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #666;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>LEMP Stack Deployed Successfully</h1>

        <p>Your LEMP (Linux, Nginx, MySQL, PHP) stack is up and running.</p>

        <div class="info-grid">
            <div class="label">PHP Version:</div>
            <div class="value success"><?= $php_version ?></div>

            <div class="label">MySQL Extension:</div>
            <div class="value success"><?= $mysql_available ?></div>

            <div class="label">Web Server:</div>
            <div class="value"><?= $server_software ?></div>

            <div class="label">Document Root:</div>
            <div class="value"><?= $document_root ?></div>

            <div class="label">Current Time:</div>
            <div class="value"><?= date('Y-m-d H:i:s') ?></div>
        </div>

        <h2>Stack Components</h2>
        <ul>
            <li><strong>L</strong>inux - Operating system</li>
            <li><strong>E</strong>ngine X (Nginx) - Web server</li>
            <li><strong>M</strong>ySQL - Database server</li>
            <li><strong>P</strong>HP - Server-side scripting</li>
        </ul>

        <div class="footer">
            Deployed with <a href="https://github.com/gleicon/cook-py">Cook</a>
        </div>
    </div>
</body>
</html>
""",
    mode=0o644,
    owner="www-data",
    group="www-data")

# PHP info page (useful for debugging)
File(
    f"{WEB_ROOT}/info.php",
    content="""<?php
phpinfo();
?>
""",
    mode=0o644,
    owner="www-data",
    group="www-data")

# Nginx Configuration

print("Configuring Nginx")

nginx_conf = File(
    "/etc/nginx/sites-available/default",
    content=f"""
server {{
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name {DOMAIN};
    root {WEB_ROOT};
    index index.php index.html index.htm;

    # Logging
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Main location
    location / {{
        try_files $uri $uri/ /index.php?$query_string;
    }}

    # PHP-FPM configuration
    location ~ \\.php$ {{
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }}

    # Deny access to hidden files
    location ~ /\\. {{
        deny all;
    }}

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
}}
""",
    mode=0o644)

# Test nginx configuration
Exec("test-nginx",
     command="nginx -t")

# PHP Configuration

print("Configuring PHP")

# PHP configuration
File(
    "/etc/php/8.1/fpm/conf.d/99-custom.ini",
    content="""
; Custom PHP configuration
upload_max_filesize = 32M
post_max_size = 32M
max_execution_time = 60
memory_limit = 128M
display_errors = Off
log_errors = On
error_log = /var/log/php-fpm-errors.log
date.timezone = UTC
""",
    mode=0o644)

# Services

print("Starting services")

# PHP-FPM
php_service = Service("php8.1-fpm",
                      running=True,
                      enabled=True)

# Nginx (reload on config changes)
Service("nginx",
        running=True,
        enabled=True,
        reload_on=[nginx_conf])

# Post-Installation Info

print(f"""
LEMP Stack installation complete

Access your application:
- Main page: http://{DOMAIN}/
- PHP info: http://{DOMAIN}/info.php

Services:
- Nginx: sudo systemctl status nginx
- MySQL: sudo systemctl status mysql
- PHP-FPM: sudo systemctl status php8.1-fpm

Configuration:
- Web root: {WEB_ROOT}
- Nginx config: /etc/nginx/sites-available/default
- PHP config: /etc/php/8.1/fpm/conf.d/99-custom.ini

MySQL:
- Root password: {MYSQL_ROOT_PASSWORD}
- Connect: mysql -u root -p

Logs:
- Nginx access: /var/log/nginx/access.log
- Nginx error: /var/log/nginx/error.log
- PHP errors: /var/log/php-fpm-errors.log
- MySQL error: /var/log/mysql/error.log

Next Steps:
1. Visit http://{DOMAIN}/ to verify installation
2. Create your database: mysql -u root -p -e "CREATE DATABASE myapp;"
3. Deploy your PHP application to {WEB_ROOT}
4. Remove info.php in production: rm {WEB_ROOT}/info.php

SECURITY NOTES:
- Change MySQL root password
- Delete info.php before going to production
- Configure SSL/TLS (Let's Encrypt recommended)
- Set up firewall rules
- Configure backups
""")
