"""
WordPress with PostgreSQL Database

Complete WordPress deployment with:
- PostgreSQL database
- Nginx web server
- PHP-FPM
- WordPress installation
- Database initialization

Designed for Ubuntu/Debian systems.

Usage:
    sudo cook plan examples/wordpress-pgsql.py
    sudo cook apply examples/wordpress-pgsql.py --yes

After deployment:
    Visit http://localhost to complete WordPress setup
"""

from cook import Package, File, Service, Exec

# Configuration
DB_NAME = "wordpress"
DB_USER = "wordpress"
DB_PASSWORD = "wordpress_secure_password_change_me"
DOMAIN = "localhost"
WEB_ROOT = "/var/www/wordpress"

# System Updates

print("Installing system packages")

# Install PostgreSQL
Package("postgresql", packages=[
    "postgresql",
    "postgresql-contrib",
    "python3-psycopg2",  # For database management
])

# Install Nginx
Package("nginx")

# Install PHP and extensions
Package("php", packages=[
    "php-fpm",
    "php-pgsql",         # PostgreSQL support
    "php-curl",
    "php-gd",
    "php-mbstring",
    "php-xml",
    "php-xmlrpc",
    "php-zip",
])

# Install utilities
Package("utils", packages=["curl", "unzip"])

# PostgreSQL Database Setup

print("Configuring PostgreSQL")

# Create database
Exec("create-db",
     command=f"sudo -u postgres psql -c \"CREATE DATABASE {DB_NAME};\"",
     unless=f"sudo -u postgres psql -lqt | cut -d \\| -f 1 | grep -qw {DB_NAME}")

# Create user
Exec("create-db-user",
     command=f"""sudo -u postgres psql -c "CREATE USER {DB_USER} WITH PASSWORD '{DB_PASSWORD}';" """,
     unless=f"sudo -u postgres psql -c \"\\du\" | grep -q {DB_USER}")

# Grant privileges
Exec("grant-db-privileges",
     command=f"""sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE {DB_NAME} TO {DB_USER};" """)

# PostgreSQL should be running
Service("postgresql", running=True, enabled=True)

# Web Directory Setup

print("Setting up web directories")

# Create web root
File(WEB_ROOT,
     ensure="directory",
     mode=0o755)

# Download WordPress
Exec("download-wordpress",
     command=f"curl -o /tmp/wordpress.zip https://wordpress.org/latest.zip",
     creates="/tmp/wordpress.zip")

# Extract WordPress
Exec("extract-wordpress",
     command=f"unzip -q /tmp/wordpress.zip -d /tmp/ && cp -r /tmp/wordpress/* {WEB_ROOT}/",
     creates=f"{WEB_ROOT}/wp-config-sample.php")

# Set ownership
Exec("set-wordpress-ownership",
     command=f"chown -R www-data:www-data {WEB_ROOT}")

# WordPress Configuration

print("Configuring WordPress")

# WordPress config with PostgreSQL support
# Note: WordPress doesn't natively support PostgreSQL, need PG4WP plugin
wp_config = File(
    f"{WEB_ROOT}/wp-config.php",
    content=f"""<?php
/**
 * WordPress Configuration
 * Generated by Cook
 */

// PostgreSQL database settings
define('DB_NAME', '{DB_NAME}');
define('DB_USER', '{DB_USER}');
define('DB_PASSWORD', '{DB_PASSWORD}');
define('DB_HOST', 'localhost');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');

// Security keys (generate new ones for production!)
define('AUTH_KEY',         'put your unique phrase here');
define('SECURE_AUTH_KEY',  'put your unique phrase here');
define('LOGGED_IN_KEY',    'put your unique phrase here');
define('NONCE_KEY',        'put your unique phrase here');
define('AUTH_SALT',        'put your unique phrase here');
define('SECURE_AUTH_SALT', 'put your unique phrase here');
define('LOGGED_IN_SALT',   'put your unique phrase here');
define('NONCE_SALT',       'put your unique phrase here');

// WordPress table prefix
$table_prefix = 'wp_';

// Debug mode (disable in production!)
define('WP_DEBUG', false);

// Absolute path
if ( !defined('ABSPATH') )
    define('ABSPATH', dirname(__FILE__) . '/');

// WordPress settings
require_once(ABSPATH . 'wp-settings.php');
?>
""",
    mode=0o644)

# Note: For actual PostgreSQL support, you'd need to:
# 1. Install PG4WP plugin
# 2. Configure WordPress to use it
# For this example, we'll use MySQL instead (more common)

# Alternative: Use MySQL/MariaDB instead
print("Note: This example uses PostgreSQL, but WordPress requires")
print("   the PG4WP plugin for PostgreSQL support. Consider using MySQL/MariaDB")
print("   for production WordPress deployments.")

# Nginx Configuration

print("Configuring Nginx")

nginx_conf = File(
    "/etc/nginx/sites-available/wordpress",
    content=f"""
server {{
    listen 80;
    server_name {DOMAIN};

    root {WEB_ROOT};
    index index.php index.html index.htm;

    # Logging
    access_log /var/log/nginx/wordpress_access.log;
    error_log /var/log/nginx/wordpress_error.log;

    # WordPress permalinks
    location / {{
        try_files $uri $uri/ /index.php?$args;
    }}

    # PHP-FPM configuration
    location ~ \\.php$ {{
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }}

    # Deny access to hidden files
    location ~ /\\. {{
        deny all;
    }}

    # WordPress uploads size limit
    client_max_body_size 64M;
}}
""",
    mode=0o644)

# Enable site
Exec("enable-wordpress-site",
     command="ln -sf /etc/nginx/sites-available/wordpress /etc/nginx/sites-enabled/wordpress",
     creates="/etc/nginx/sites-enabled/wordpress")

# Remove default site
Exec("remove-default-nginx",
     command="rm -f /etc/nginx/sites-enabled/default",
     unless="test ! -f /etc/nginx/sites-enabled/default")

# Test nginx config
Exec("test-nginx-config",
     command="nginx -t")

# PHP-FPM Configuration

print("Configuring PHP-FPM")

# Increase PHP upload limits
php_ini = File(
    "/etc/php/8.1/fpm/conf.d/99-wordpress.ini",
    content="""
upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 300
memory_limit = 256M
""",
    mode=0o644)

# Services

print("Starting services")

# PHP-FPM with reload on config changes
Service("php8.1-fpm",
        running=True,
        enabled=True,
        reload_on=[php_ini])

# Nginx with reload on config changes
Service("nginx",
        running=True,
        enabled=True,
        reload_on=[nginx_conf])

# Post-Installation

print("""
WordPress installation complete

Next steps:
1. Visit http://{DOMAIN} to complete WordPress setup
2. Follow the WordPress installation wizard
3. Change database password in production!
4. Generate new security keys: https://api.wordpress.org/secret-key/1.1/salt/

Database Info:
- Database: {DB_NAME}
- User: {DB_USER}
- Password: {DB_PASSWORD}
- Host: localhost

Files:
- Web root: {WEB_ROOT}
- Nginx config: /etc/nginx/sites-available/wordpress
- PHP config: /etc/php/8.1/fpm/conf.d/99-wordpress.ini

Services:
- PostgreSQL: sudo systemctl status postgresql
- PHP-FPM: sudo systemctl status php8.1-fpm
- Nginx: sudo systemctl status nginx

Logs:
- Nginx access: /var/log/nginx/wordpress_access.log
- Nginx error: /var/log/nginx/wordpress_error.log
- PHP-FPM: /var/log/php8.1-fpm.log

SECURITY WARNING:
This is a basic setup for development/testing.
For production:
- Change all passwords
- Generate new WordPress security keys
- Configure SSL/TLS (Let's Encrypt)
- Set up backups
- Configure firewall
- Review file permissions
""".format(DOMAIN=DOMAIN, DB_NAME=DB_NAME, DB_USER=DB_USER,
           DB_PASSWORD=DB_PASSWORD, WEB_ROOT=WEB_ROOT))
