"""
Code generator for recording mode.

Converts parsed resources into Python code.
"""

from typing import List, Dict, Any
from cook.record.parser import ParsedResource


class CodeGenerator:
    """
    Generate Python code from parsed resources.

    Converts ParsedResource objects into executable Cook configurations.
    """

    def __init__(self):
        self.imports = set()

    def generate(self, resources: List[ParsedResource]) -> str:
        """
        Generate Python code from resources.

        Args:
            resources: List of ParsedResource objects

        Returns:
            Python code as string
        """
        self.imports.clear()

        # Group resources by type
        packages = [r for r in resources if r.type == 'package']
        files = [r for r in resources if r.type == 'file']
        services = [r for r in resources if r.type == 'service']
        commands = [r for r in resources if r.type == 'exec']

        # Determine required imports
        if packages:
            self.imports.add('Package')
        if files:
            self.imports.add('File')
        if services:
            self.imports.add('Service')
        if commands:
            self.imports.add('Exec')

        # Generate code sections
        parts = []

        # Header
        parts.append('"""')
        parts.append('Generated by Cook recording mode.')
        parts.append('"""')
        parts.append('')

        # Imports
        if self.imports:
            imports_str = ', '.join(sorted(self.imports))
            parts.append(f'from cook import {imports_str}')
            parts.append('')

        # Resources
        if packages:
            parts.append('# Package installations')
            for resource in packages:
                parts.append(self._generate_package(resource))
            parts.append('')

        if files:
            parts.append('# File operations')
            for resource in files:
                parts.append(self._generate_file(resource))
            parts.append('')

        if services:
            parts.append('# Service management')
            for resource in services:
                parts.append(self._generate_service(resource))
            parts.append('')

        if commands:
            parts.append('# Command executions')
            for resource in commands:
                parts.append(self._generate_command(resource))
            parts.append('')

        return '\n'.join(parts)

    def _generate_package(self, resource: ParsedResource) -> str:
        """Generate Package resource code."""
        data = resource.data
        name = data['name']

        if data.get('packages'):
            packages = data['packages']
            packages_str = ', '.join(f'"{p}"' for p in packages)
            return f'Package("{name}", packages=[{packages_str}])'
        else:
            return f'Package("{name}")'

    def _generate_file(self, resource: ParsedResource) -> str:
        """Generate File resource code."""
        data = resource.data
        path = data['path']
        args = []

        if 'ensure' in data:
            args.append(f'ensure="{data["ensure"]}"')

        if 'mode' in data:
            args.append(f'mode={oct(data["mode"])}')

        if 'owner' in data:
            args.append(f'owner="{data["owner"]}"')

        if 'group' in data:
            args.append(f'group="{data["group"]}"')

        if 'content' in data:
            content = data['content'].replace('"', '\\"')
            args.append(f'content="{content}"')

        args_str = ', '.join(args)
        if args_str:
            return f'File("{path}", {args_str})'
        else:
            return f'File("{path}")'

    def _generate_service(self, resource: ParsedResource) -> str:
        """Generate Service resource code."""
        data = resource.data
        name = data['name']
        args = []

        if 'running' in data:
            args.append(f'running={data["running"]}')

        if 'enabled' in data:
            args.append(f'enabled={data["enabled"]}')

        args_str = ', '.join(args)
        return f'Service("{name}", {args_str})'

    def _generate_command(self, resource: ParsedResource) -> str:
        """Generate Exec resource code."""
        data = resource.data
        name = data['name']
        command = data['command']
        args = [f'command="{command}"']

        if 'creates' in data:
            args.append(f'creates="{data["creates"]}"')

        if 'unless' in data:
            args.append(f'unless="{data["unless"]}"')

        args_str = ', '.join(args)
        return f'Exec("{name}", {args_str})'

    def generate_from_history(self, history_file: str) -> str:
        """
        Generate code from shell history file.

        Args:
            history_file: Path to shell history file

        Returns:
            Generated Python code
        """
        from cook.record.parser import CommandParser

        with open(history_file, 'r') as f:
            lines = f.readlines()

        parser = CommandParser()
        resources = parser.parse_history(lines)

        return self.generate(resources)
